### ISSUE TITLE
Can't pass audio file via WIPs to DFA

### ISSUE THREAD

**Issue by rickgonzalez** [guy-stewart/AzariaCD#2]
Playwave will play an audio file but I can't pass it to the dfa using WIP1 or WIP2 which would be helpful.

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><title></title><meta name="generator" content="DB Browser for SQLite"><meta name="date" content="YYYY-04-DDT19:20:13.048"><style type="text/css">br{mso-data-placement:same-cell;}</style></head><body>

M_ORIESPEAKER | 0 | 1 | O_ACCEPT | 0 | IDD_SPEAKER
-- | -- | -- | -- | -- | --
M_ORIESPEAKER | 1 | 2 | DROP | 0 | 0
M_ORIESPEAKER | 2 | 3 | ASSIGN | WOBJECT | IDD_SPEAKER
M_ORIESPEAKER | 3 | 4 | SHOW | WOBJECT |  
M_ORIESPEAKER | 4 | 5 | PLAYWAVE | 0 | SOUND_ORIE1
M_ORIESPEAKER | 5 | 6 | GRAB | 0 | 0
M_ORIESPEAKER | 6 | 1 | SHOW | 0 | 0

The above works - just now when replacing SOUND_ORIE WITH WIP2 OR OTHER WIPS FROM THE MACHINE

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><title></title><meta name="generator" content="DB Browser for SQLite"><meta name="date" content="YYYY-04-DDT19:21:53.840"><style type="text/css">br{mso-data-placement:same-cell;}</style></head><body>

220 | S03_SPEAKERSTANDa | 200 | IDV_ORIE | 2416 | 169 | 2442 | 200 | 0 | M_ORIESPEAKER |   |   | SOUND_ORIE1 | 0 |   | 0 |   | 0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

</body></html>

</body></html>`

**Comment by guy-stewart** [comment]
Fixed in MacOS v.0.0.12

**Comment by rickgonzalez** [comment]
fixed in .0.12
