### ISSUE TITLE
Audio files from effects via playwave interrupt and stop game music

### ISSUE THREAD

**Issue by rickgonzalez** [guy-stewart/AzariaCD#3]
Background music started via the views tables should play through underneath narration or sound effects.

**Comment by guy-stewart** [comment]
This is a limitation of the new wave player for macOS. The issue will be resolved once the new wave module is completed.

**Comment by guy-stewart** [comment]
This is fixed in the latest build. I’ll post it with the next set of fixes.

**Comment by rickgonzalez** [comment]
validated to be fixed lol
